### ISSUE TITLE
[FR-8] Contact The Team

### ISSUE THREAD

**Issue by UmarA2002** [WSU-4110/PageTurners#11]
### Goal

If the user has any questions, they may get in touch with us, the website creators.

### Description

The user may fill out a form to contact us if they have any questions or just need assistance with administrative tasks, and we will get back to them within 24 hours. Name, email address, and questions will be requested on the form. In case that the form is not submitted, they can reach us via email, which is available on the website.

### Stakeholders

Users

### Date

0/20/2024

### Version

1.0

### Origin

meeting 9/20/2024

**Comment by alkhafaji4** [comment]
Did not add this feature
