### ISSUE TITLE
[FR-16] Notification

### ISSUE THREAD

**Issue by UmarA2002** [WSU-4110/PageTurners#12]
### Goal

The user will be notified of ongoing changes in their book clubs.

### Description

The system will have notifications for ongoing changes in a user's book clubs, as well as any other interactions on posts they have made. These notifications will be displayed on the home screen.

### Stakeholders

Users

### Date

9/20/2024

### Version

1.0

### Origin

meeting 9/18/2024

### Priority of the proposed feature

Don't Need

**Comment by alkhafaji4** [comment]
Did not add this feature
