### ISSUE TITLE
[NFR-4] Website Availability 

### ISSUE THREAD

**Issue by UmarA2002** [WSU-4110/PageTurners#15]
### Goal

the site will run constantly

### Description

The site will be available for the user to access for all hours of the day. The site will only be down for minimal maintenance.

### Stakeholders

users

### Date

9/20/2024

### Version

1.0

### Origin

meeting 9/20/2024

### Priority of the proposed feature

Should have

**Comment by alkhafaji4** [comment]
Site is available
