### ISSUE TITLE
[FR-14] Book Review System

### ISSUE THREAD

**Issue by benS-03** [WSU-4110/PageTurners#3]
### Goal

Internal Book Club Review System

### Description

Within a book club users should be able to review books read as a part of the club separately. Theses reviews should then be aggregated into a group score, displayed on a page listing books a club has read with this aggregate score.

### Stakeholders

Administrators, users

### Date

September 19, 2024

### Version

1.0

### Origin

Meeting September 18, 2024

### Priority of the proposed feature

Could have

**Comment by alkhafaji4** [comment]
Did not add this feature
