### ISSUE TITLE
[FR-12] Profile Customization

### ISSUE THREAD

**Issue by benS-03** [WSU-4110/PageTurners#4]
### Goal

Basic user profile customization

### Description

Users should be able to customize their profile with basic options including profile picture and bio. Other users should be able to then visit the customized profile

### Stakeholders

Users

### Date

September 19, 2024

### Version

1.0

### Origin

Meeting September 18, 2024

### Priority of the proposed feature

Could have

**Comment by alkhafaji4** [comment]
Users can change book club names and image
